trigger: none  # Запускается вручную или по триггеру из resources

pr: none

resources:
  pipelines:
  - pipeline: ciPipeline
    source: 'Verydeli-azure-piplines-ci'  # Имя вашего CI pipeline
    trigger:
      branches:
        include:
          - master

pool:
  name: 'Default'

variables:
  artifactName: 'nextjs-app'
  output_location: 'app'

stages:
- stage: Deploy
  jobs:
  - job: DeployStaticApp
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        pipeline: 'Verydeli-azure-piplines-ci'
        buildVersionToDownload: 'latest'
        artifact: $(artifactName)
        path: $(System.DefaultWorkingDirectory)/$(output_location)
      displayName: 'Download build artifact'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: '.'                      # Папка с исходниками приложения, обычно корень
        output_location: '$(output_location)' # Путь к собранному приложению
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      displayName: 'Deploy to Azure Static Web App'
