
# Node.js with Next.js
# Build a Node.js project that uses Next.js.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js 18.x'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm run build'
  env:
    # Define your build-time environment variables here.
    # These are mapped from secret variables configured in your Azure DevOps pipeline settings.
    # NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: $(NEXT_PUBLIC_GOOGLE_MAPS_API_KEY_SECRET)
    GEMINI_API_KEY: $(GEMINI_API_KEY_SECRET) # Map the secret variable to GEMINI_API_KEY
    CI: true # Often used by build tools to optimize output

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build' # Corresponds to distDir in next.config.ts
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'Copy build output to staging'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    ArtifactName: 'nextjs-app'
    publishLocation: 'Container'
  displayName: 'Publish artifact: nextjs-app'

