trigger:
- master

pool:
  name: 'Default'

variables:
  imageName: 'verydeli'
  acrLoginServer: 'verydeli.azurecr.io'
  azureSubscription: 'verydeli'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js 18.x'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm run build'
  env:
    GEMINI_API_KEY: $(GEMINI_API_KEY_SECRET)
    CI: true

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: buildAndPush
    repository: '$(acrLoginServer)/$(imageName)'
    dockerfile: 'Dockerfile'
    containerRegistry: '$(azureSubscription)'
    tags: |
      $(Build.BuildId)

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'Copy build output to staging'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    ArtifactName: 'nextjs-app'
    publishLocation: 'Container'
  displayName: 'Publish artifact: nextjs-app'
