trigger: none  # Run manually or based on artifact

pr: none

pool:
  name: 'Default'  # Use your self-hosted agent pool, same as CI

variables:
  artifactName: 'nextjs-app'
  output_location: 'app'  # Matches the CI artifact folder name

stages:
- stage: Deploy
  displayName: 'Deploy to Azure Static Web App'
  jobs:
  - job: DeployStaticApp
    displayName: 'Deploy job'
    steps:

    # Download build artifact from CI
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: $(artifactName)
        path: $(System.DefaultWorkingDirectory)/$(output_location)
      displayName: 'Download build artifact'

    # Deploy to Azure Static Web App using token
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '.'
        output_location: '$(output_location)'
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      displayName: 'Deploy to Azure Static Web App'
